{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.2/core-2.2.module",
    "group": "ren.shiror.fvv",
    "module": "core",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-2.2.jar",
          "size": 58811,
          "sha512": "12243f769efe38956d2de4259093dace866426619655c4af8287a119f60294e42346277801a0e873f84943b59e14214e70443c2f67c0f5d068c0625cf75be1dd",
          "sha256": "c16d3c9e395a831419bbfa759cc340497cfdf95b9314c60078c60a6f67a64044",
          "sha1": "ca72cf41dd37c721ea542454bb19579b88ffd362",
          "md5": "bc72dd232d8b84605b0821eadd99b8ec"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "core-jvm-2.2.jar",
          "size": 58811,
          "sha512": "12243f769efe38956d2de4259093dace866426619655c4af8287a119f60294e42346277801a0e873f84943b59e14214e70443c2f67c0f5d068c0625cf75be1dd",
          "sha256": "c16d3c9e395a831419bbfa759cc340497cfdf95b9314c60078c60a6f67a64044",
          "sha1": "ca72cf41dd37c721ea542454bb19579b88ffd362",
          "md5": "bc72dd232d8b84605b0821eadd99b8ec"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "core-jvm-2.2-sources.jar",
          "size": 8998,
          "sha512": "78c400f65207e60273b19a34d9f97415f2499330a94cd8095b547394b56663ee0277855898089426357f04cf865fb6c488d14d077b528e13fb16e701b5e7be3c",
          "sha256": "354afeb1ada2c2beb46e2c3eccb7dc621a7c6b9c983b732926c35684c3098010",
          "sha1": "358ce7f55705227f350153219d502bf692fdb7c8",
          "md5": "5679cb3b79025933f36726c08e27b7be"
        }
      ]
    }
  ]
}
